language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
      env: GRADLE_PUBLISH=true
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
dist: trusty
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c59ebaa474a68d9af2b6
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - secure: X7ZTQ/2tDjHrJU5INm+6sXDxlNhmT9bm0SPfJ8T7dQAh9ucGJQdoZxAkByd1eEA9XIEa0guMFNJPQ94Oibmp7HEYK5uoL/ChP+jztviFw2L/QamW0bjgfP1nmVs7MqOtQ4PbxMm0AB+pUfFgPjMqS3pD7mKdt4kx30Fvg4il7PU=
  - secure: g7zSHuXYT+9V0zTpoSykCaOaerVE0Cj14ME1C+c+aE6EJEQSswpCcJyvhMKf4rSkMCdnUeuRDR5ZkQARfk9ouphsA0Nvs9+4zyWjiyu6JSOmD7+jTsRBhQmrkW0ZKYxE5DHBZHAt35gV/rN6AP8AEtzBAu96tCX5ISwhIJrdPyI=
  - secure: zgAhmzbPg8h27HCn/IbBbrI9v5JHoG5PJFrqHhDinxv4w691B4AK1f6qUgLaBosnBxA1xw35MhqrOxtbt0C1WcsMs5x4wkVV7jbFGpIo06l2r8GpcjUm+BGLyR6fVJrr0jinDJluwnTjiRZtdxkfab7TzmHETWZssjrDrga/NfQ=
  - secure: e6top+DJXytcMTakF7HnxiiM4Hv6XdbmZ393TGERZiBYwZ1tfWKuVSYGnrVbdbaijCZLg6znC+QsNrmUrhyqdLe3xn9twrghUodFbMjSx0czit9TuzsL7sFD7zPiGxdfkbEJoOe+rFUmkKrJ4jifU7eeDFHm87fibBXJCYoX6cA=
  - secure: NQQH6G4ORscavTnoiq4DSIo71SSpyIipo2zFe3X8W/Fh5FEI50v019CIAOtkQldY4uswJJsv6khGL6FoyaOgNZ/2CeDZ5INiiZC//yl24fkFibIenC8/kXjGYSTCcuV4HK21uqsmaXTiddL2WPPPuOJSLpq6Fnt91hmdORHkkLk=
  - secure: yJMk1H4MKMTq67zd9W4HIxWdeTa3qIv3msAdPqDH6kwGmvSDzV3eChAT5iw2BtvEF7Ykt8hFpE1qsn82iDKQf27RlrGw7B7SvnDPa5ZItgXef/2MHJf5JoFGO4N5DUnumxFDy2UZz3I7X/XgoNRdYPfa5gIDH14Pjmvz5aAqzKc=
  - secure: JVGR1mpUvsvjNWiEe+0uK7yi5kB23+uSKHA3+8nvD5xEdw6QxRvzuPfnbOmzXXe4a/It9Xjr7apNrdb0TTzMop+IB0AEDgWElX0LwZgk9KaAD3sLZzFMN85HxxIHMRI5ZnYJugSBp4Pmz89PN8C0zbkGAqdoQ+oWG3RJcoCeMBs=
