language: java
sudo: false
jdk: openjdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_90ab3804b7e3_key -iv $encrypted_90ab3804b7e3_iv -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c59ebaa474a68d9af2b6
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
